name: Publish Package
on:
  push:
    branches: [ git_workflow ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test 
      - name: Run coverage
        run: npm run coverage 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
           token: ${{ secrets.CODECOV_TOKEN }}

  publish-npm:
    needs: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y oathtool
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
      - run: npm publish --otp="$(oathtool -b --totp ${{secrets.NPM_SECRET_KEY}})"
